config/routes.rb
Rails.application.routes.draw do
  get 'jans/search'
  get 'jans/index'
   resources :jans do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :JAN
  belongs_to :Manufacturer
  belongs_to :Product
  belongs_to :Quantity
end

app/models/jan.rb
class Jan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart

  def current_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, only: [:add_item, :update_item, :delete_item]

  def show
    @cart_items = current_cart.cart_items
  end

  # 商品一覧画面から、「商品購入」を押した時のアクション
  def add_item
    if @cart_item.blank?
      @cart_item = current_cart.cart_items.build(product_id: params[:JAN])
    end

    @cart_item.quantity += params[:quantity].to_i
    @cart_item.save
    redirect_to current_cart
  end

  # カート詳細画面から、「更新」を押した時のアクション
  def update_item
    @cart_item.update(quantity: params[:quantity].to_i)
    redirect_to current_cart
  end

　# カート詳細画面から、「削除」を押した時のアクション
  def delete_item
    @cart_item.destroy
    redirect_to current_cart
  end

  private

  def setup_cart_item!
    @cart_item = current_cart.cart_items.find_by(product_id: params[:product_id])
  end
end

app/controllers/jans_controller.rb
class JansController < ApplicationController
  def index
    @jans = Jan.all
  end
  
  before_action :set_q, only: [:index, :search]
  def search
    @results = @q.result
    @jans = Jan.all
    @cart_items = CartItem.all
  end
  def set_q
    @q = Jan.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jans_helper.rb
module JansHelper
end

app/views/jans/index.html.erb
<h1>JANコード、メーカー名、シリーズ名や商品名で検索</h1>
<%= search_form_for @q, url: search_jans_path do |f| %>
  <%= f.label :JAN_cont , 'JANコード' %>
  <%= f.search_field :JAN_cont %>
  <%= f.label :Manufacturer_cont , 'メーカー名' %>
  <%= f.search_field :Manufacturer_cont %>
  <%= f.label :Product_cont , 'シリーズ名や商品名' %>
  <%= f.search_field :Product_cont %>
  <%= f.submit '検索' %>
<% end %>

app/views/jans/search.html.erb
<h1>JANコード、メーカー名、シリーズ名や商品名で検索</h1>
<%= search_form_for @q, url: search_jans_path do |f| %>
  <%= f.label :JAN_cont , 'JANコード' %>
  <%= f.search_field :JAN_cont %>
  <%= f.label :Manufacturer_cont , 'メーカー名' %>
  <%= f.search_field :Manufacturer_cont %>
  <%= f.label :Product_cont , 'シリーズ名や商品名' %>
  <%= f.search_field :Product_cont %>
  <%= f.submit '検索' %>
<% end %>

<h1>@cart_item</h1>
<table>
  <thead>
    <tr>
      <th>JANコード</th>
      <th>Manufacturer</th>
      <th>Product</th>
      <th>Quabtity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @cart_items.nil? %>
    <td>商品を追加してください</td>
    <% else %>
      <% @cart_items.each do |jan| %>
        <tr>
          <td><%= jan.JAN %></td>
          <td><%= jan.Manufacturer %></td>
          <td><%= jan.Product %></td>
          <td><%= jan.quantity %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h1>@results</h1>
<table>
  <thead>
    <tr>
      <th>JANコード</th>
      <th>Manufacturer</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @results.nil? %>
      <td>商品が見つかりませんでした</td>
    <% else %>
      <% @results.each do |jan| %>
        <%= form_with model: @cart_item do |f| %>
          <tr>
            <td><%= jan.JAN %></td>
            <td><%= jan.Manufacturer %></td>
            <td><%= jan.Product %></td>
            <td><%= f.submit "カートへ追加", class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<h1>@jans</h1>
<table>
  <thead>
    <tr>
      <th>JANコード</th>
      <th>Manufacturer</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @jans.nil? %>
      <td>商品が見つかりませんでした</td>
    <% else %>
      <% @jans.each do |jan| %>
        <tr>
          <td><%= jan.JAN %></td>
          <td><%= jan.Manufacturer %></td>
          <td><%= jan.Product %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JanCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>